sync to drive python script + custom action
beyond-all-reason/maps-metadata pull request #79
Opened 2023-07-02 22:02 UTC by fntyler

Added `.github/actions/` dir

to store custom actions that are local to the repository.

Added `.github/actions/sync-to-drive-action/` dir

to store specific action, "sync-to-drive-action" action

Added `.github/actions/sync-to-drive-action/action.yml`

logic for the composite action (action meta-data file)

Added `.github/actions/sync-to-drive-action/syncgdrive.py`

python script that will handle the getting, putting, and deleting of files in google drive folder.

python script is not complete, however, the base logic has been strucuted.

2023-07-02 22:12 UTC, fntyler commented
Come to think of it, I'm sure there are better way to execute this script in a workflow using a more _mature_ public GitHub Action.

2023-07-03 19:09 UTC, p2004a requested changes
I see the script is pretty incomplete as you wrote, so not commenting any more on it, just skimmed over it.

Overall about the approach, I think that creating custom action is good idea if we have a need for strong encapsulation of functionality or we want to reuse it. It's not the case for this syncing, so I recommend you instead just integrate it in https://github.com/beyond-all-reason/maps-metadata/blob/main/.github/workflows/ci.yaml as yet another deploy step.

https://github.com/beyond-all-reason/maps-metadata/tree/main/scripts/py is probably good location, and the workflow already has the steps with example that install deps etc.

2023-07-03 19:09 UTC, p2004a commented on .github/actions/sync-to-drive-action/syncgdrive.py
> +            if d1.keys() <= d2.keys():
I don't understand, why do you call `.keys()` on key?

2023-07-03 19:09 UTC, p2004a commented on .github/actions/sync-to-drive-action/syncgdrive.py
> +def compare_dicts(dict1, dict2):
Instead of writing your own implementation of diffing, you should switch to using sets and use standard python set operators.

2023-07-03 19:09 UTC, p2004a commented on .github/actions/sync-to-drive-action/syncgdrive.py
> +#!/usr/bin/env python3
Optional but would be appreciated: use typing annotations and verify with mypy, e.g. like I do in this unfinished script here: https://github.com/beyond-all-reason/maps-metadata/pull/59

Typing annotations greatly improve readability and catch easy errors.

2023-07-17 15:32 UTC, closed without merging